// <auto-generated />
using System;
using EmitScheduler.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmitScheduler.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514095720_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmitScheduler.API.Models.Cours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.EmploiDuTemps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HeureFin")
                        .HasColumnType("time");

                    b.Property<int>("Jour")
                        .HasColumnType("integer");

                    b.Property<int>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfesseurId")
                        .HasColumnType("integer");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("ProfesseurId");

                    b.HasIndex("SalleId");

                    b.ToTable("EmploisDuTemps");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroEtudiant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NiveauId");

                    b.HasIndex("NumeroEtudiant")
                        .IsUnique();

                    b.ToTable("Etudiants");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Mention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Mentions");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Niveau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Groupe")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("MentionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MentionId", "Code", "Groupe")
                        .IsUnique();

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Professeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Professeurs");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.ProfesseurCours", b =>
                {
                    b.Property<int>("ProfesseurId")
                        .HasColumnType("integer");

                    b.Property<int>("CoursId")
                        .HasColumnType("integer");

                    b.HasKey("ProfesseurId", "CoursId");

                    b.HasIndex("CoursId");

                    b.ToTable("ProfesseurCours");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.ProfesseurMention", b =>
                {
                    b.Property<int>("ProfesseurId")
                        .HasColumnType("integer");

                    b.Property<int>("MentionId")
                        .HasColumnType("integer");

                    b.HasKey("ProfesseurId", "MentionId");

                    b.HasIndex("MentionId");

                    b.ToTable("ProfesseurMentions");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<int>("NiveauId")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NiveauId")
                        .IsUnique();

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("EtudiantId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProfesseurId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Etudiant");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EtudiantId")
                        .IsUnique();

                    b.HasIndex("ProfesseurId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.EmploiDuTemps", b =>
                {
                    b.HasOne("EmitScheduler.API.Models.Cours", "Cours")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitScheduler.API.Models.Niveau", "Niveau")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitScheduler.API.Models.Professeur", "Professeur")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("ProfesseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmitScheduler.API.Models.Salle", "Salle")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Niveau");

                    b.Navigation("Professeur");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Etudiant", b =>
                {
                    b.HasOne("EmitScheduler.API.Models.Niveau", "Niveau")
                        .WithMany("Etudiants")
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Niveau", b =>
                {
                    b.HasOne("EmitScheduler.API.Models.Mention", "Mention")
                        .WithMany("Niveaux")
                        .HasForeignKey("MentionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mention");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.ProfesseurCours", b =>
                {
                    b.HasOne("EmitScheduler.API.Models.Cours", "Cours")
                        .WithMany("ProfesseurCours")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmitScheduler.API.Models.Professeur", "Professeur")
                        .WithMany("ProfesseurCours")
                        .HasForeignKey("ProfesseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.ProfesseurMention", b =>
                {
                    b.HasOne("EmitScheduler.API.Models.Mention", "Mention")
                        .WithMany("ProfesseurMentions")
                        .HasForeignKey("MentionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmitScheduler.API.Models.Professeur", "Professeur")
                        .WithMany("ProfesseurMentions")
                        .HasForeignKey("ProfesseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mention");

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Salle", b =>
                {
                    b.HasOne("EmitScheduler.API.Models.Niveau", "Niveau")
                        .WithOne("Salle")
                        .HasForeignKey("EmitScheduler.API.Models.Salle", "NiveauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Niveau");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.User", b =>
                {
                    b.HasOne("EmitScheduler.API.Models.Etudiant", "Etudiant")
                        .WithOne("User")
                        .HasForeignKey("EmitScheduler.API.Models.User", "EtudiantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EmitScheduler.API.Models.Professeur", "Professeur")
                        .WithOne("User")
                        .HasForeignKey("EmitScheduler.API.Models.User", "ProfesseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Etudiant");

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Cours", b =>
                {
                    b.Navigation("EmploisDuTemps");

                    b.Navigation("ProfesseurCours");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Etudiant", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Mention", b =>
                {
                    b.Navigation("Niveaux");

                    b.Navigation("ProfesseurMentions");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Niveau", b =>
                {
                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Etudiants");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Professeur", b =>
                {
                    b.Navigation("EmploisDuTemps");

                    b.Navigation("ProfesseurCours");

                    b.Navigation("ProfesseurMentions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmitScheduler.API.Models.Salle", b =>
                {
                    b.Navigation("EmploisDuTemps");
                });
#pragma warning restore 612, 618
        }
    }
}
